type Block @entity {
  id: ID! # Block number as string
  height: Int! @index
  hash: String!
  timestamp: DateTime! @index
  transactions: [Transaction] @derivedFrom(field: "block")
  logs: [Log] @derivedFrom(field: "block")
  traces: [Trace] @derivedFrom(field: "block")
  erc20Transfers: [Erc20Transfer] @derivedFrom(field: "block")
  erc721Transfers: [Erc721Transfer] @derivedFrom(field: "block")
}

type Transaction @entity {
  id: ID! # tx hash
  block: Block! @index
  blockNumber: Int! @index
  hash: String! @index
  from: String! @index
  to: String
  value: BigInt!
  gasUsed: BigInt!
}

type Log @entity {
  id: ID!
  block: Block! @index
  blockNumber: Int! @index
  transactionHash: String @index
  address: String! @index
  topic0: String @index
  data: String
}

type Trace @entity {
  id: ID!
  block: Block! @index
  blockNumber: Int! @index
  transactionHash: String @index
  from: String! @index
  to: String @index
  type: String!
  value: BigInt
}

type Erc20Transfer @entity {
  id: ID! # {txHash}-{logIndex}
  block: Block! @index
  blockNumber: Int! @index
  transactionHash: String @index
  contractAddress: String! @index
  from: String! @index
  to: String! @index
  value: BigInt!
}

type Erc721Transfer @entity {
  id: ID! # {txHash}-{logIndex}
  block: Block! @index
  blockNumber: Int! @index
  transactionHash: String @index
  contractAddress: String! @index
  from: String! @index
  to: String! @index
  tokenId: BigInt! @index
}